name: strip_markdown

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '>=3.10'

      - name: Set up environment
        run: pip install --upgrade -q -r requirements.txt

      - name: Lint (flake8)
        run: |
          python -m flake8 strip_markdown --count --select=E9,F63,F7,F82 --show-source --statistics
          python -m flake8 strip_markdown --count --exit_zero --max_complexity=10 --statistics

      - name: Build strip_markdown
        run: python -m build

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags') # Only publish tagged commits
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
